/**
 * Report Generator — produces downloadable CSV/text reports from design data.
 * PDF generation uses browser print. Excel uses CSV with .xlsx-friendly formatting.
 */

import type { DesignInputs } from "@/stores/designInputsStore";
import type { Recommendations } from "@/components/modules/designInputs/recommendationEngine";
import { buildValveClassTable } from "@/components/modules/designInputs/valveClassTableEngine";
import {
  pressureUnit,
  stressUnit,
  lengthUnit,
  tempUnit,
  normalizePressureToBar,
  normalizeStressToMPa,
  normalizeLengthToMM,
  MM_TO_IN,
  MPA_TO_KSI,
  type UnitSystem,
} from "@/lib/unitConversion";
import { ENGINEERING_REVIEW_NOTICE, PRODUCT_NAME } from "@/lib/brand";
import { DATASET_RELEASE_ATTESTATION_TEXT } from "@/lib/appVersion";

export interface ReportData {
  inputs: DesignInputs;
  recommendations: Recommendations;
  overrides: Record<string, boolean>;
  activePipeMaterial: string;
  calculated: boolean;
}

function fmt(v: string | number | null | undefined, fallback = "—"): string {
  if (v === null || v === undefined || v === "") return fallback;
  return String(v);
}

function section(title: string, rows: [string, string][]): string {
  const lines = [`\n${"=".repeat(60)}`, title, "=".repeat(60)];
  for (const [label, value] of rows) {
    lines.push(`${label.padEnd(35)} ${value}`);
  }
  return lines.join("\n");
}

function getUnitContext(unitSystem: string) {
  const us: UnitSystem = unitSystem === "Imperial" ? "Imperial" : "SI";
  const pUnit = pressureUnit(us);
  const sUnit = stressUnit(us);
  const lUnit = lengthUnit(us);
  const tUnit = tempUnit(us);
  const formatLengthFromMm = (mm: number, decimalsSI = 2, decimalsImp = 3) =>
    us === "SI" ? `${mm.toFixed(decimalsSI)} ${lUnit}` : `${(mm * MM_TO_IN).toFixed(decimalsImp)} ${lUnit}`;
  return { us, pUnit, sUnit, lUnit, tUnit, formatLengthFromMm };
}

const REPORT_DISCLAIMER =
  `DISCLAIMER: ${ENGINEERING_REVIEW_NOTICE}`;
const REPORT_RELEASE_ATTESTATION =
  `RELEASE ATTESTATION:\n${DATASET_RELEASE_ATTESTATION_TEXT}\nApplies to the bundled dataset package only; not project approval or checker sign-off.`;

function getThicknessInputs(data: ReportData) {
  const { inputs: i, recommendations: r, overrides: o } = data;
  const { us } = getUnitContext(i.unitSystem);
  const P_mpa = normalizePressureToBar(i.designPressure, us) * 0.1;
  const D_mm = normalizeLengthToMM(r.pipeOD?.value || "0", us);
  const S_mpa = normalizeStressToMPa(r.allowableStress?.value || "0", us);
  const Ej = parseFloat(o.jointQualityFactor ? i.jointQualityFactor : r.jointQualityFactor.value) || 1;
  const CA_mm = normalizeLengthToMM(o.corrosionAllowance ? i.corrosionAllowance : r.corrosionAllowance.value, us);
  const MT = parseFloat(o.millTolerance ? i.millTolerance : r.millTolerance.value) || 12.5;
  const Y = 0.4;
  const tDesign = S_mpa > 0 ? (P_mpa * D_mm) / (2 * (S_mpa * Ej + P_mpa * Y)) : 0;
  const tCorr = tDesign + CA_mm;
  const tMin = tCorr / (1 - MT / 100);
  return { P_mpa, D_mm, S_mpa, Ej, CA_mm, MT, Y, tDesign, tCorr, tMin };
}

// ===================== LINE DESIGN SUMMARY =====================

export function generateLineSummary(data: ReportData): string {
  const { inputs: i, recommendations: r, overrides: o, activePipeMaterial } = data;
  const { pUnit, sUnit, lUnit, tUnit, formatLengthFromMm } = getUnitContext(i.unitSystem);
  const { tDesign, tCorr, tMin } = getThicknessInputs(data);

  const report = [
    "=" .repeat(60),
    "ASME B31.3 PROCESS PIPING — LINE DESIGN SUMMARY",
    "=" .repeat(60),
    `Report Date: ${new Date().toLocaleDateString()}`,
    `Generated by: ${PRODUCT_NAME}`,
    "",
    REPORT_RELEASE_ATTESTATION,
    "",
    REPORT_DISCLAIMER,

    section("PROJECT INFORMATION", [
      ["Project Name:", fmt(i.projectName)],
      ["Line Number:", fmt(i.lineNumber)],
      ["Service Description:", fmt(i.serviceDescription)],
      ["Service Type:", fmt(i.serviceType)],
      ["Fluid Phase:", fmt(i.fluidPhase)],
      ["Piping Category:", fmt(i.pipingCategory)],
      ["Unit System:", fmt(i.unitSystem)],
    ]),

    section("DESIGN CONDITIONS", [
      ["Design Pressure:", `${fmt(i.designPressure)} ${pUnit}`],
      ["Design Temperature:", `${fmt(i.designTemperature)} ${tUnit}`],
      ["Operating Pressure:", `${fmt(i.operatingPressure)} ${pUnit}`],
      ["Operating Temperature:", `${fmt(i.operatingTemperature)} ${tUnit}`],
      ["Test Pressure:", `${fmt(o.testPressure ? i.testPressure : r.testPressure.value)} ${pUnit}`],
      ["Test Medium:", fmt(o.testMedium ? i.testMedium : r.testMedium.value)],
    ]),

    section("MATERIAL SELECTIONS", [
      ["Pipe Material:", `${fmt(activePipeMaterial)} ${o.pipeMaterial ? "(Manual Override)" : "(Recommended)"}`],
      ["  Basis:", r.pipeMaterial.reason],
      ["  Source:", r.pipeMaterial.source],
      ["Flange Material:", `${fmt(o.flangeMaterial ? i.flangeMaterial : r.flangeMaterial.value)} ${o.flangeMaterial ? "(Override)" : "(Recommended)"}`],
      ["  Basis:", r.flangeMaterial.reason],
      ["Fitting Material:", `${fmt(o.fittingMaterial ? i.fittingMaterial : r.fittingMaterial.value)} ${o.fittingMaterial ? "(Override)" : "(Recommended)"}`],
      ["  Basis:", r.fittingMaterial.reason],
      ["Bolt Material:", `${fmt(o.boltMaterial ? i.boltMaterial : r.boltMaterial.value)} ${o.boltMaterial ? "(Override)" : "(Recommended)"}`],
      ["  Basis:", r.boltMaterial.reason],
      ["Gasket Type:", `${fmt(o.gasketType ? i.gasketType : r.gasketType.value)} ${o.gasketType ? "(Override)" : "(Recommended)"}`],
      ["  Basis:", r.gasketType.reason],
    ]),

    section("DESIGN PARAMETERS", [
      ["Allowable Stress (S):", r.allowableStress ? `${r.allowableStress.value} ${sUnit} — ${r.allowableStress.tableRef}` : "—"],
      ["Flange Class:", r.flangeClass ? `${r.flangeClass.value} — ${r.flangeClass.tableRef}` : "—"],
      ["Pipe OD:", r.pipeOD ? `${r.pipeOD.value} ${lUnit} — ${r.pipeOD.tableRef}` : "—"],
      ["NPS:", fmt(i.nominalPipeSize)],
      ["Corrosion Allowance:", `${fmt(o.corrosionAllowance ? i.corrosionAllowance : r.corrosionAllowance.value)} ${lUnit}`],
      ["Mill Tolerance:", `${fmt(o.millTolerance ? i.millTolerance : r.millTolerance.value)}%`],
      ["Joint Quality Factor (Ej):", fmt(o.jointQualityFactor ? i.jointQualityFactor : r.jointQualityFactor.value)],
      ["Weld Type:", fmt(i.weldType)],
    ]),

    section("WALL THICKNESS SUMMARY (ASME B31.3 §304.1.2)", [
      ["Design Thickness (t):", formatLengthFromMm(tDesign)],
      ["Corroded Thickness (t + CA):", formatLengthFromMm(tCorr)],
      ["Minimum Required (tmin):", formatLengthFromMm(tMin)],
      ["Formula:", "t = PD / 2(SEj + PY), Y=0.4"],
    ]),

    section("INSULATION", [
      ["Insulation Type:", fmt(i.insulationType)],
      ["Insulation Thickness:", `${fmt(i.insulationThickness)} ${lUnit}`],
    ]),

    section("SOURCE REFERENCES", [
      ["Design Code:", "ASME B31.3 Process Piping"],
      ["Stress Data:", "ASME Section II Part D, Table 1A"],
      ["Pipe Dimensions:", "ASME B36.10M"],
      ["Flange Ratings:", "ASME B16.5"],
      ["Fittings:", "ASME B16.9 / B16.11"],
    ]),

    "\n" + "=".repeat(60),
    "END OF REPORT",
    "=".repeat(60),
  ];

  return report.join("\n");
}

// ===================== THICKNESS CALC SHEET =====================

export function generateThicknessReport(data: ReportData): string {
  const { inputs: i } = data;
  const { pUnit, sUnit, lUnit, tUnit, formatLengthFromMm } = getUnitContext(i.unitSystem);
  const { P_mpa, D_mm, S_mpa, Ej, CA_mm, MT, Y, tDesign, tCorr, tMin } = getThicknessInputs(data);
  const pressureInput = parseFloat(i.designPressure) || 0;
  const stressInput = parseFloat(data.recommendations.allowableStress?.value || "0");
  const diameterInput = parseFloat(data.recommendations.pipeOD?.value || "0");
  const caInput = parseFloat((data.overrides.corrosionAllowance ? i.corrosionAllowance : data.recommendations.corrosionAllowance.value) || "0");

  return [
    "PIPE WALL THICKNESS CALCULATION — ASME B31.3 §304.1.2",
    "=".repeat(60),
    `Line: ${fmt(i.lineNumber)} | NPS: ${fmt(i.nominalPipeSize)} | Material: ${fmt(data.activePipeMaterial)}`,
    "",
    "INPUT PARAMETERS",
    "-".repeat(40),
    `Design Pressure (P):        ${pressureInput} ${pUnit} → ${P_mpa.toFixed(4)} MPa`,
    `Outside Diameter (D):       ${diameterInput} ${lUnit} → ${D_mm.toFixed(3)} mm  [ASME B36.10M]`,
    `Allowable Stress (S):       ${stressInput} ${sUnit} → ${S_mpa.toFixed(3)} MPa  [ASME Sec II-D, Table 1A @ ${fmt(i.designTemperature)}${tUnit}]`,
    `Joint Quality Factor (Ej):  ${Ej}  [ASME B31.3 Table 302.3.4]`,
    `Coefficient Y:              ${Y}  [ASME B31.3 Table 304.1.1, t < D/6]`,
    `Corrosion Allowance (CA):   ${caInput} ${lUnit} → ${CA_mm.toFixed(3)} mm`,
    `Mill Tolerance:             ${MT}%`,
    "",
    "CALCULATION STEPS",
    "-".repeat(40),
    `Step 1: Design thickness`,
    `  t = PD / 2(SEj + PY)`,
    `  t = ${P_mpa.toFixed(4)} × ${D_mm.toFixed(3)} / 2(${S_mpa.toFixed(3)} × ${Ej} + ${P_mpa.toFixed(4)} × ${Y})`,
    `  t = ${(P_mpa * D_mm).toFixed(4)} / ${(2 * (S_mpa * Ej + P_mpa * Y)).toFixed(4)}`,
    `  t = ${formatLengthFromMm(tDesign, 3, 3)}`,
    "",
    `Step 2: Add corrosion allowance`,
    `  t_corr = t + CA = ${formatLengthFromMm(tDesign, 3, 3)} + ${caInput} ${lUnit} = ${formatLengthFromMm(tCorr, 3, 3)}`,
    "",
    `Step 3: Apply mill tolerance`,
    `  t_min = t_corr / (1 - MT/100)`,
    `  t_min = ${formatLengthFromMm(tCorr, 3, 3)} / (1 - ${MT}/100)`,
    `  t_min = ${formatLengthFromMm(tMin, 3, 3)}`,
    "",
    "RESULT",
    "-".repeat(40),
    `Minimum Required Wall Thickness: ${formatLengthFromMm(tMin, 2, 3)}`,
    "",
    "REFERENCES",
    `- ASME B31.3-2022, §304.1.2`,
    `- ASME Sec II Part D, Table 1A (${fmt(data.activePipeMaterial)})`,
    `- ASME B36.10M (Pipe Dimensions)`,
    "",
    REPORT_RELEASE_ATTESTATION,
    "",
    REPORT_DISCLAIMER,
  ].join("\n");
}

// ===================== MATERIAL RECOMMENDATION =====================

export function generateMaterialReport(data: ReportData): string {
  const { inputs: i, recommendations: r, overrides: o } = data;
  const { pUnit, tUnit } = getUnitContext(i.unitSystem);
  const valveClassTable = buildValveClassTable({
    pipeMaterial: o.pipeMaterial ? i.pipeMaterial : r.pipeMaterial.value,
    serviceType: i.serviceType,
    corrosionSeverity: i.corrosionSeverity,
    designTemperature: i.designTemperature,
    designPressure: i.designPressure,
    serviceDescription: i.serviceDescription,
    flangeClass: r.flangeClass?.value,
  });
  const valveRows = valveClassTable.rows
    .filter((row) => ["Gate Valve", "Globe Valve", "Check Valve", "Ball Valve"].includes(row.valveType))
    .map((row) => `${row.valveType}: Body ${row.body}; Trim ${row.trim}; Seat ${row.seat}; ${row.ratingClass}; Ends ${row.ends}`);
  return [
    "MATERIAL / COMPONENT RECOMMENDATION REPORT",
    "=".repeat(60),
    `Line: ${fmt(i.lineNumber)} | Service: ${fmt(i.serviceType)}`,
    `Design: ${fmt(i.designPressure)} ${pUnit} @ ${fmt(i.designTemperature)}${tUnit}`,
    "",
    "PIPE MATERIAL",
    "-".repeat(40),
    `Selected:    ${fmt(o.pipeMaterial ? i.pipeMaterial : r.pipeMaterial.value)}`,
    `Status:      ${o.pipeMaterial ? "Manual Override" : "Recommended"}`,
    `Basis:       ${r.pipeMaterial.reason}`,
    `Source:      ${r.pipeMaterial.source}`,
    `Confidence:  ${r.pipeMaterial.confidence}`,
    `Alternatives: ${r.pipeMaterial.options.join(", ")}`,
    "",
    "FLANGE MATERIAL",
    "-".repeat(40),
    `Selected:    ${fmt(o.flangeMaterial ? i.flangeMaterial : r.flangeMaterial.value)}`,
    `Status:      ${o.flangeMaterial ? "Manual Override" : "Recommended"}`,
    `Basis:       ${r.flangeMaterial.reason}`,
    `Source:      ${r.flangeMaterial.source}`,
    "",
    "FITTING MATERIAL",
    "-".repeat(40),
    `Selected:    ${fmt(o.fittingMaterial ? i.fittingMaterial : r.fittingMaterial.value)}`,
    `Status:      ${o.fittingMaterial ? "Manual Override" : "Recommended"}`,
    `Basis:       ${r.fittingMaterial.reason}`,
    `Source:      ${r.fittingMaterial.source}`,
    "",
    "BOLT MATERIAL",
    "-".repeat(40),
    `Selected:    ${fmt(o.boltMaterial ? i.boltMaterial : r.boltMaterial.value)}`,
    `Status:      ${o.boltMaterial ? "Manual Override" : "Recommended"}`,
    `Basis:       ${r.boltMaterial.reason}`,
    `Source:      ${r.boltMaterial.source}`,
    "",
    "GASKET TYPE",
    "-".repeat(40),
    `Selected:    ${fmt(o.gasketType ? i.gasketType : r.gasketType.value)}`,
    `Status:      ${o.gasketType ? "Manual Override" : "Recommended"}`,
    `Basis:       ${r.gasketType.reason}`,
    `Source:      ${r.gasketType.source}`,
    "",
    "VALVE MATERIALS",
    "-".repeat(40),
    ...valveRows,
    `Basis:       Valve materials are generated from the same valve class table used by Material Selection and PMS.`,
    `Source:      ASME B16.34 / API 600 / API 602 / API 608 / API 594`,
    "",
    "REFERENCES",
    `- ASME B31.3 (material compatibility rules)`,
    `- ASME Sec II-D (allowable stress data)`,
    `- ASME B16.5 (flange ratings)`,
    `- NACE MR0175 (if sour service)`,
    "",
    REPORT_RELEASE_ATTESTATION,
    "",
    REPORT_DISCLAIMER,
  ].join("\n");
}

// ===================== FLANGE & BOLTING DATASHEET =====================

export function generateFlangeBoltReport(data: ReportData): string {
  const { inputs: i, recommendations: r, overrides: o } = data;
  const { pUnit, tUnit } = getUnitContext(i.unitSystem);
  return [
    "FLANGE & BOLTING DATASHEET",
    "=".repeat(60),
    `Line: ${fmt(i.lineNumber)} | NPS: ${fmt(i.nominalPipeSize)}`,
    "",
    "FLANGE DETAILS",
    "-".repeat(40),
    `Flange Material:  ${fmt(o.flangeMaterial ? i.flangeMaterial : r.flangeMaterial.value)}`,
    `Flange Class:     ${r.flangeClass ? r.flangeClass.value : "—"}`,
    `Rating Basis:     ${r.flangeClass ? r.flangeClass.reason : "Insufficient data"}`,
    `Source:           ${r.flangeClass ? r.flangeClass.tableRef : "—"}`,
    "",
    "BOLTING DETAILS",
    "-".repeat(40),
    `Bolt Material:    ${fmt(o.boltMaterial ? i.boltMaterial : r.boltMaterial.value)}`,
    `Bolt Basis:       ${r.boltMaterial.reason}`,
    `Source:           ${r.boltMaterial.source}`,
    "",
    "GASKET DETAILS",
    "-".repeat(40),
    `Gasket Type:      ${fmt(o.gasketType ? i.gasketType : r.gasketType.value)}`,
    `Gasket Basis:     ${r.gasketType.reason}`,
    "",
    "DESIGN CONDITIONS",
    "-".repeat(40),
    `Design Pressure:     ${fmt(i.designPressure)} ${pUnit}`,
    `Design Temperature:  ${fmt(i.designTemperature)} ${tUnit}`,
    "",
    "REFERENCES",
    `- ASME B16.5 (P-T ratings)`,
    `- ASME B16.20 (gaskets)`,
    `- ASME B31.3 (bolting rules)`,
    "",
    REPORT_RELEASE_ATTESTATION,
    "",
    REPORT_DISCLAIMER,
  ].join("\n");
}

// ===================== SUPPORT RECOMMENDATION =====================

export function generateSupportReport(data: ReportData): string {
  const { inputs: i } = data;
  const { lUnit } = getUnitContext(i.unitSystem);
  return [
    "PIPE SUPPORT RECOMMENDATION SHEET",
    "=".repeat(60),
    `Line: ${fmt(i.lineNumber)} | NPS: ${fmt(i.nominalPipeSize)}`,
    `Material: ${fmt(data.activePipeMaterial)}`,
    `Insulation: ${fmt(i.insulationType)} ${fmt(i.insulationThickness)}${lUnit}`,
    "",
    "NOTE: Run Support Span module for detailed span calculations.",
    "Support span values are calculated using beam deflection formula per:",
    "- ASME B31.1 Table 121.5 (guideline)",
    "- MSS SP-69 (Pipe Hangers and Supports)",
    "- Deflection limit: 2.5mm per span",
    "",
    "INPUT BASIS",
    "-".repeat(40),
    `NPS:                 ${fmt(i.nominalPipeSize)}`,
    `Pipe Material:       ${fmt(data.activePipeMaterial)}`,
    `Fluid Phase:         ${fmt(i.fluidPhase)}`,
    `Insulation Type:     ${fmt(i.insulationType)}`,
    `Insulation Thick.:   ${fmt(i.insulationThickness)} ${lUnit}`,
    "",
    REPORT_RELEASE_ATTESTATION,
    "",
    REPORT_DISCLAIMER,
  ].join("\n");
}

// ===================== B31.3 CHECKLIST =====================

export function generateChecklistReport(data: ReportData): string {
  const { inputs: i } = data;
  const checks = [
    ["Material per B31.3 Table A-1", data.activePipeMaterial ? "✓ Selected" : "○ Pending"],
    ["Allowable stress per Sec II-D", data.recommendations.allowableStress ? "✓ Looked up" : "○ Pending"],
    ["Wall thickness per §304.1.2", data.calculated ? "✓ Calculated" : "○ Not yet run"],
    ["Flange rating per B16.5", data.recommendations.flangeClass ? "✓ Determined" : "○ Pending"],
    ["Pipe schedule per B36.10M", i.nominalPipeSize ? "✓ Available" : "○ Pending"],
    ["Corrosion allowance defined", (i.corrosionAllowance || data.recommendations.corrosionAllowance.value) ? "✓ Set" : "○ Pending"],
    ["Test pressure defined", (i.testPressure || data.recommendations.testPressure.value) ? "✓ Set" : "○ Pending"],
    ["Service classification", i.serviceType ? "✓ Classified" : "○ Pending"],
    ["Category M evaluation", i.categoryM ? "✓ Evaluated" : "○ Pending"],
    ["Severe cyclic check", i.severeCyclic ? "✓ Evaluated" : "○ Pending"],
    ["Support spacing", i.supportSpacing ? "✓ Defined" : "○ Pending"],
  ];

  const lines = [
    "ASME B31.3 DESIGN REVIEW WORKSHEET",
    "=".repeat(60),
    `Line: ${fmt(i.lineNumber)} | Date: ${new Date().toLocaleDateString()}`,
    "",
    "CHECK ITEM".padEnd(42) + "STATUS",
    "-".repeat(60),
  ];
  for (const [item, status] of checks) {
    lines.push(`${item.padEnd(42)} ${status}`);
  }
  lines.push("", REPORT_RELEASE_ATTESTATION, "", REPORT_DISCLAIMER);
  return lines.join("\n");
}

// ===================== AUDIT TRAIL =====================

export function generateAuditReport(data: ReportData): string {
  const { inputs: i, recommendations: r, overrides: o } = data;
  const entries: [string, string, string][] = [];
  
  const addEntry = (field: string, value: string, source: string) => {
    entries.push([field, value || "—", source]);
  };

  addEntry("Service Type", i.serviceType, "User Input");
  addEntry("Design Pressure", `${i.designPressure} ${pressureUnit(i.unitSystem === "Imperial" ? "Imperial" : "SI")}`, "User Input");
  addEntry("Design Temperature", `${i.designTemperature} ${tempUnit(i.unitSystem === "Imperial" ? "Imperial" : "SI")}`, "User Input");
  addEntry("Pipe Material", data.activePipeMaterial, o.pipeMaterial ? "Manual Override" : `Recommended: ${r.pipeMaterial.source}`);
  addEntry("Flange Material", o.flangeMaterial ? i.flangeMaterial : r.flangeMaterial.value, o.flangeMaterial ? "Manual Override" : `Recommended: ${r.flangeMaterial.source}`);
  addEntry("Bolt Material", o.boltMaterial ? i.boltMaterial : r.boltMaterial.value, o.boltMaterial ? "Manual Override" : `Recommended: ${r.boltMaterial.source}`);
  addEntry("Gasket Type", o.gasketType ? i.gasketType : r.gasketType.value, o.gasketType ? "Manual Override" : `Recommended: ${r.gasketType.source}`);
  addEntry("Allowable Stress", r.allowableStress ? `${r.allowableStress.value} ${stressUnit(i.unitSystem === "Imperial" ? "Imperial" : "SI")}` : "", r.allowableStress?.tableRef || "Not looked up");
  addEntry("Flange Class", r.flangeClass?.value || "", r.flangeClass?.tableRef || "Not determined");
  addEntry("Corrosion Allowance", `${o.corrosionAllowance ? i.corrosionAllowance : r.corrosionAllowance.value} ${lengthUnit(i.unitSystem === "Imperial" ? "Imperial" : "SI")}`, o.corrosionAllowance ? "Manual Override" : r.corrosionAllowance.source);
  addEntry("Mill Tolerance", o.millTolerance ? i.millTolerance : r.millTolerance.value, o.millTolerance ? "Manual Override" : "Default 12.5%");
  addEntry("Joint Quality Factor", o.jointQualityFactor ? i.jointQualityFactor : r.jointQualityFactor.value, o.jointQualityFactor ? "Manual Override" : r.jointQualityFactor.source);

  const lines = [
    "AUDIT TRAIL REPORT",
    "=".repeat(80),
    `Line: ${fmt(i.lineNumber)} | Date: ${new Date().toLocaleDateString()}`,
    "",
    "FIELD".padEnd(25) + "VALUE".padEnd(25) + "SOURCE / BASIS",
    "-".repeat(80),
  ];
  for (const [field, value, source] of entries) {
    lines.push(`${field.padEnd(25)} ${value.padEnd(25)} ${source}`);
  }

  lines.push(
    "",
    "ASSUMPTIONS",
    "-".repeat(40),
    "- Y coefficient = 0.4 (per B31.3 Table 304.1.1, t < D/6)",
    "- Temperature interpolation: linear between table values",
    "- All recommendations based on built-in engineering rules",
    "",
    REPORT_RELEASE_ATTESTATION,
    "",
    REPORT_DISCLAIMER,
  );
  return lines.join("\n");
}

// ===================== DOWNLOAD HELPERS =====================

export function downloadAsText(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadAsCsv(content: string, filename: string): void {
  // Convert text report to simple CSV-friendly format
  const blob = new Blob([content], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function printReport(content: string, title: string): void {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(`
    <html><head><title>${escapeHtml(title)}</title>
    <style>
      body { font-family: 'Courier New', monospace; font-size: 11px; white-space: pre; padding: 20px; }
      @media print { body { margin: 0; } }
    </style>
    </head><body>${escapeHtml(content)}</body></html>
  `);
  printWindow.document.close();
  printWindow.print();
}

export type ReportId = "line-summary" | "thickness" | "material" | "flange-bolt" | "support" | "b313-checklist" | "audit-trail";

export function getReportContent(id: ReportId, data: ReportData): { content: string; title: string } {
  switch (id) {
    case "line-summary":
      return { content: generateLineSummary(data), title: "Line_Design_Summary" };
    case "thickness":
      return { content: generateThicknessReport(data), title: "Thickness_Calculation" };
    case "material":
      return { content: generateMaterialReport(data), title: "Material_Recommendation" };
    case "flange-bolt":
      return { content: generateFlangeBoltReport(data), title: "Flange_Bolting_Datasheet" };
    case "support":
      return { content: generateSupportReport(data), title: "Support_Recommendation" };
    case "b313-checklist":
      return { content: generateChecklistReport(data), title: "B313_Design_Checklist" };
    case "audit-trail":
      return { content: generateAuditReport(data), title: "Audit_Trail" };
  }
}
